spring:
  application:
    name: branding-backend

  datasource:
    url: jdbc:mysql://localhost:3306/branding
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: root1234!

  jpa:
    hibernate:
      ddl-auto: update

  sql:
    init:
      mode: never

cloud:
  aws:
    credentials:
      access-key: YOUR_ACCESS_KEY
      secret-key: SECRET_KEY
    region:
      static: ap-northeast-2
    s3:
      bucket: branding-backend-image-bucket
    stack:
      auto: false

jwt:
  secret: branding-backend-jwt-secret-key-2026
  access-token-expiration: 3600000