spring:
  application:
    name: branding-backend

  datasource:
    url: jdbc:mysql://branding-mysql.cxcac08uaf1x.ap-northeast-2.rds.amazonaws.com:3306/branding
      ?serverTimezone=Asia/Seoul
      &characterEncoding=UTF-8
      &useSSL=false
      &allowPublicKeyRetrieval=true
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: admin
    password: root1234!

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
    properties:
      hibernate:
        format_sql: false

server:
  port: 8080

jwt:
  secret: branding-backend-jwt-secret-key-2026-secure!!
  access-token-expiration: 3600000